basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^todos/(?P<pk>\d+)/$', views.todos, name="todos"),
    url(r'^delete/(?P<pk>\d+)/$', views.delete, name="delete"),
    url(r'^done/(?P<pk>\d+)/$', views.done, name="done"),
    url(r'^undone/(?P<pk>\d+)/$', views.undone, name="undone"),
    url(r'^edit/(?P<pk>\d+)/$', views.edit, name="edit"),

    url(r'^add_todo/$', views.addTodo, name="addTodo"),

    url(r'^$', views.user_login, name="user_login"),
    url(r'^register/$', views.register, name="register"),
    url(r'^user_logout/$', views.user_logout, name="user_logout"),



]

todo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('basic_app.urls')),
    url(r'^api/', include('basic_app.api.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/docs/', include('rest_framework_docs.urls')),

]

templates/add_todo.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}


{% block body_block %}

  <div class="w3-card-4">
  <div class="w3-container">
    <h3><span style="color:#52af50;">Add New Todo</span></h3>
  </div>
  <form class="w3-container" method="post">
    {% csrf_token %}

    <p>
    <label class="w3-text-brown"><b>Todo Title: </b></label>
    {% render_field form1.title class="form-control w3-input w3-border w3-light-grey" placeholder="" %}</p>
    <p>
    <label class="w3-text-brown"><b>Scheduled Time: </b></label>
      {% render_field form1.scheduled_time id="datetimepicker1" class="form-control w3-input w3-border w3-light-grey" placeholder="" %}</p>
    <p>
    <input class="w3-btn w3-green" type="submit" value="Add Todo"></p>
  </form>
</div>



<!-- <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
 <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script>
 $( function() {
   $( "#datepicker" ).datepicker({
   dateFormat: "yy-mm-dd"
 });

 } );
 </script> -->
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.css"/>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>


 <script>
   $(function () {
     $('#datetimepicker1').datetimepicker({
         format:'Y-m-d h:m:s'
     });
  });
 </script>


<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"> -->
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Todo List</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<link rel="stylesheet" type="text/css" href={% static "css/index.css" %}>
  <link rel="stylesheet" type="text/css" href="/jquery.datetimepicker.css"/ >


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>


  </head>
  <body style="background:#fcfcfc;">




<div class="w3-bar w3-green w3-large">
  <a href="{% url 'basic_app:todos' request.user.pk %}" class="w3-bar-item w3-button">Todo List</a>
  <a href="{% url 'basic_app:addTodo' %}" class="w3-bar-item w3-button">Add Todo</a>
  {% if user.is_authenticated %}
  <a href="#" style="text-decoration:none" class="w3-bar-item">Welcome, {{user.username}}</a>
  <a href="{% url 'basic_app:user_logout' %}" class="w3-bar-item w3-button w3-red w3-right">Logout</a>
  {% endif %}
</div>

    <div class="w3-container">
      <br>
      {% block body_block %}

      {% endblock %}
    </div>


  </body>
</html>

templates/edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% load staticfiles %}

{% block body_block %}

<div class="w3-card-4">
<div class="w3-container">
  <h3><span style="color:#52af50;">Edit Todo</span></h3>
</div>
<form class="w3-container" method="post">
  {% csrf_token %}

  <p>
  <label class="w3-text-brown"><b>Todo Title: </b></label>
  {% render_field form.title class="form-control w3-input w3-border w3-light-grey" value=data.title  %}</p>
  <p>
  <label class="w3-text-brown"><b>Scheduled Time: </b></label>
  {% render_field form.scheduled_time class="form-control w3-input w3-border w3-light-grey" id="datetimepicker1" value=data.scheduled_time %}</p>
  <p>
  <input class="w3-btn w3-green" type="submit" value="Edit Todo"></p>
</form>
</div>


<!---------------------------------------->


<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.css"/>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>


 <script>
   $(function () {
     $('#datetimepicker1').datetimepicker({
         format:'Y-m-d h:m:s'
     });
  });
 </script>

{% endblock %}

templates/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Todo List</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
  </head>
  <body>

<div class="login-page">
  <div class="form">
    <h1 style="color:#4CAF50;">Login Here</h1>
    <form class="login-form" action="{% url 'basic_app:user_login' %}" method="post">
      {% csrf_token %}

      <input type="text" placeholder="Username" name="username"/>
      <input type="password" placeholder="Password" name="password"/>
      <input type="submit" value="Login">
      <p class="message">Not registered? <a href="{% url 'basic_app:register' %}">Create an account</a></p>
    </form>
  </div>
</div>

  </body>
</html>

templates/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Todo List</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
  </head>
  <body>

<div class="login-page">
  <div class="form">
    <h1>Signup Here</h1>
    <form class="login-form" method="post">
      {% csrf_token %}

      {{ form1.as_p }}
      <input type="submit" value="Register">
      <p class="message">Already registered? <a href="{% url 'basic_app:user_login' %}">Login Here</a></p>
    </form>
  </div>
</div>

  </body>
</html>

templates/todos.html
{% extends 'base.html' %}

{% block body_block %}

{% if messages %}

  {% for message in messages %}
  <div class="w3-panel w3-pale-green w3-display-container">
    <span onclick="this.parentElement.style.display='none'"
    class="w3-button w3-large w3-display-topright">&times;</span>

    <p>{{message}}</p>
  </div>

  {% endfor %}

{% endif %}

<table class="w3-table-all w3-bordered w3-card-4">
  <tr>
    <th>Title</th>
    <th>Completed</th>
    <th>Delete Todo</th>
  </tr>
{% for todo in data1 %}
  {% if todo.completed %}
    <tr class="w3-blue">
      <td style="text-decoration:line-through"><a style="color:#ffffff; text-decoration:none;" href="{% url 'basic_app:edit' todo.pk %}">{{ todo.title }}</a></td>
      <td><a style="color:#ffffff; text-decoration:none;" href="{% url 'basic_app:undone' todo.pk %}">Undone</a></td>
      <td><a style="color:#ffffff; text-decoration:none;" href="{% url 'basic_app:delete' todo.pk %}">Delete</a></td>
    </tr>
    {% else %}
    <tr>
      <td><a style="color:#424242; text-decoration:none;" href="{% url 'basic_app:edit' todo.pk %}">{{ todo.title }}</a></td>
      <td><a style="color:#424242; text-decoration:none;" href="{% url 'basic_app:done' todo.pk %}">Done</a></td>
      <td><a style="color:#424242; text-decoration:none;" href="{% url 'basic_app:delete' todo.pk %}">Delete</a></td>
    </tr>
    {% endif %}
{% endfor %}
</table>

{% endblock %}